<?php 
	$deck = isset($_POST['scroll']) ? ($ScrollController->autoGeneratedDeck($_POST['scroll'], $_POST['relatedNum'])) : "";
 ?>

<div class="container">
	<div class="col-6 col-offset-3">
		<form method="post" action="">
			<div class="form-element">
				<label>Scroll ID:
					<input type="text" name="scroll" id="scrolls" value="" />
				</label>
			</div>
			<div class="form-element">
				<label>Number of Related Scrolls:
					<select name="relatedNum" id="relatedNum">
						<option value="3">3</option>
						<option value="5" selected="selected">5</option>
						<option value="7">7</option>
						<option value="10">10</option>
					</select>
				</label>
			</div>
			<div class="form-element align-center">
				<button class="success btn big" type="submit">Test</button>
			</div>
			<div class="form-element">
				<textarea rows="10"><?= $deck[0] ?></textarea>
			</div>
		</form>
	</div>
	<div class="col-12">
		<h3><?= $deck[2] ?></h3>
		<pre><?= print_r($deck[1]) ?></pre>
	</div>
</div>